import type {
  BookingCase,
  Draft,
  Interaction,
  MockEmailLog,
  SeedPayload,
  TimelineEntry,
} from "@/lib/types";

const cases: BookingCase[] = [
  {
    id: "case_001",
    state: "fit_review",
    client_email: "jane.kim@example.com",
    client_name: "Jane Kim",
    source: "squarespace_form",
    paused_reason: "Waiting for your approval before the system can proceed",
    current_step: "Ready for your review",
    created_at: "2026-04-05T09:30:00-07:00",
    updated_at: "2026-04-05T14:16:00-07:00",
  },
  {
    id: "case_002",
    state: "cancel_requested",
    client_email: "tom.r@example.com",
    client_name: "Tom R.",
    source: "squarespace_form",
    paused_reason: "Escalated to you — the system has stepped back",
    current_step: "Cancellation requested",
    created_at: "2026-04-09T08:00:00-07:00",
    updated_at: "2026-04-09T11:43:00-07:00",
  },
  {
    id: "case_003",
    state: "awaiting_client_confirmation",
    client_email: "marcus.l@example.com",
    client_name: "Marcus L.",
    source: "squarespace_form",
    paused_reason: null,
    current_step: "Waiting on client",
    created_at: "2026-04-07T10:00:00-07:00",
    updated_at: "2026-04-08T09:02:00-07:00",
  },
  {
    id: "case_004",
    state: "booked",
    client_email: "sarah.m@example.com",
    client_name: "Sarah M.",
    source: "squarespace_form",
    paused_reason: null,
    current_step: "Booked ✓",
    created_at: "2026-04-03T11:00:00-07:00",
    updated_at: "2026-04-05T09:01:00-07:00",
  },
];

const timeline: TimelineEntry[] = [
  {
    id: "timeline_001",
    case_id: "case_001",
    type: "event",
    content: "Booking inquiry received via Squarespace form",
    timestamp: "Apr 5, 9:30 AM",
  },
  {
    id: "timeline_002",
    case_id: "case_001",
    type: "action",
    content: "System sent intake email",
    metadata: { automation_level: "auto", action: "send_intake_email" },
    timestamp: "Apr 5, 9:31 AM",
  },
  {
    id: "timeline_003",
    case_id: "case_001",
    type: "event",
    content: "Jane replied with intake information",
    timestamp: "Apr 5, 2:14 PM",
  },
  {
    id: "timeline_004",
    case_id: "case_001",
    type: "state_change",
    content: "Case moved to: Ready for your review",
    metadata: { from_state: "intake_pending", to_state: "fit_review" },
    timestamp: "Apr 5, 2:15 PM",
  },
  {
    id: "timeline_005",
    case_id: "case_001",
    type: "draft",
    content: "Draft ready — waiting for your approval",
    metadata: { automation_level: "draft", action: "approve_fit" },
    timestamp: "Apr 5, 2:16 PM",
  },
  {
    id: "timeline_006",
    case_id: "case_002",
    type: "event",
    content: "Booking confirmed",
    timestamp: "Apr 9, 8:00 AM",
  },
  {
    id: "timeline_007",
    case_id: "case_002",
    type: "state_change",
    content: "Case moved to: Booked",
    metadata: {
      from_state: "awaiting_client_confirmation",
      to_state: "booked",
    },
    timestamp: "Apr 9, 8:01 AM",
  },
  {
    id: "timeline_008",
    case_id: "case_002",
    type: "event",
    content: "Tom requested cancellation",
    timestamp: "Apr 9, 11:42 AM",
  },
  {
    id: "timeline_009",
    case_id: "case_002",
    type: "state_change",
    content: "Case moved to: Cancellation requested",
    metadata: { from_state: "booked", to_state: "cancel_requested" },
    timestamp: "Apr 9, 11:43 AM",
  },
  {
    id: "timeline_010",
    case_id: "case_002",
    type: "system_note",
    content: "System escalated to you — no draft generated",
    metadata: { automation_level: "manual" },
    timestamp: "Apr 9, 11:43 AM",
  },
  {
    id: "timeline_011",
    case_id: "case_003",
    type: "event",
    content: "Booking inquiry received via Squarespace form",
    timestamp: "Apr 7, 10:00 AM",
  },
  {
    id: "timeline_012",
    case_id: "case_003",
    type: "action",
    content: "System sent intake email",
    metadata: { automation_level: "auto", action: "send_intake_email" },
    timestamp: "Apr 7, 10:01 AM",
  },
  {
    id: "timeline_013",
    case_id: "case_003",
    type: "event",
    content: "Marcus replied with intake information",
    timestamp: "Apr 7, 3:30 PM",
  },
  {
    id: "timeline_014",
    case_id: "case_003",
    type: "state_change",
    content: "Case moved to: Ready for your review",
    metadata: { from_state: "intake_pending", to_state: "fit_review" },
    timestamp: "Apr 7, 3:31 PM",
  },
  {
    id: "timeline_015",
    case_id: "case_003",
    type: "action",
    content: "Draft approved — fit confirmation email sent",
    metadata: { automation_level: "draft", action: "approve_fit" },
    timestamp: "Apr 8, 9:00 AM",
  },
  {
    id: "timeline_016",
    case_id: "case_003",
    type: "state_change",
    content: "Case moved to: Finding a time",
    metadata: { from_state: "fit_review", to_state: "fit_confirmed" },
    timestamp: "Apr 8, 9:01 AM",
  },
  {
    id: "timeline_017",
    case_id: "case_003",
    type: "action",
    content: "System sent available time slots",
    metadata: { automation_level: "auto", action: "propose_time_slots" },
    timestamp: "Apr 8, 9:02 AM",
  },
  {
    id: "timeline_018",
    case_id: "case_003",
    type: "state_change",
    content: "Case moved to: Waiting on client",
    metadata: {
      from_state: "fit_confirmed",
      to_state: "awaiting_client_confirmation",
    },
    timestamp: "Apr 8, 9:02 AM",
  },
  {
    id: "timeline_019",
    case_id: "case_004",
    type: "event",
    content: "Booking inquiry received via Squarespace form",
    timestamp: "Apr 3, 11:00 AM",
  },
  {
    id: "timeline_020",
    case_id: "case_004",
    type: "action",
    content: "System sent intake email",
    metadata: { automation_level: "auto", action: "send_intake_email" },
    timestamp: "Apr 3, 11:01 AM",
  },
  {
    id: "timeline_021",
    case_id: "case_004",
    type: "state_change",
    content: "Case moved to: Ready for your review",
    metadata: { from_state: "intake_pending", to_state: "fit_review" },
    timestamp: "Apr 4, 2:00 PM",
  },
  {
    id: "timeline_022",
    case_id: "case_004",
    type: "action",
    content: "Draft approved — fit confirmation email sent",
    metadata: { automation_level: "draft", action: "approve_fit" },
    timestamp: "Apr 4, 4:00 PM",
  },
  {
    id: "timeline_023",
    case_id: "case_004",
    type: "action",
    content: "System sent available time slots",
    metadata: { automation_level: "auto", action: "propose_time_slots" },
    timestamp: "Apr 4, 4:01 PM",
  },
  {
    id: "timeline_024",
    case_id: "case_004",
    type: "event",
    content: "Sarah confirmed Thursday, April 10 at 3:00 PM",
    timestamp: "Apr 4, 6:30 PM",
  },
  {
    id: "timeline_025",
    case_id: "case_004",
    type: "action",
    content: "Draft approved — booking confirmation email sent",
    metadata: { automation_level: "draft", action: "confirm_booking" },
    timestamp: "Apr 5, 9:00 AM",
  },
  {
    id: "timeline_026",
    case_id: "case_004",
    type: "state_change",
    content: "Case moved to: Booked",
    metadata: {
      from_state: "awaiting_client_confirmation",
      to_state: "booked",
    },
    timestamp: "Apr 5, 9:00 AM",
  },
  {
    id: "timeline_027",
    case_id: "case_004",
    type: "action",
    content: "Reminder scheduled for Apr 9 at 3:00 PM",
    metadata: { automation_level: "auto", action: "schedule_reminder" },
    timestamp: "Apr 5, 9:01 AM",
  },
];

const drafts: Draft[] = [
  {
    id: "draft_001",
    case_id: "case_001",
    action: "approve_fit",
    status: "pending",
    channel: "email",
    subject: "Next steps for your session",
    body: "Hi Jane, thanks for sharing more about what you're looking for. Based on what you've shared, I think this could be a great fit. I'd love to find a time to connect — I'll send over a few options shortly.",
    created_at: "2026-04-05T14:16:00-07:00",
    updated_at: "2026-04-05T14:16:00-07:00",
  },
];

const interactions: Interaction[] = [
  {
    id: "interaction_001",
    case_id: "case_001",
    channel: "web_form",
    direction: "inbound",
    content: "Jane submitted the Squarespace intake form.",
    timestamp: "2026-04-05T09:30:00-07:00",
  },
  {
    id: "interaction_002",
    case_id: "case_001",
    channel: "email",
    direction: "inbound",
    content: "Jane replied with intake information and availability preferences.",
    timestamp: "2026-04-05T14:14:00-07:00",
  },
  {
    id: "interaction_003",
    case_id: "case_002",
    channel: "email",
    direction: "inbound",
    content: "Tom asked to cancel the upcoming booking.",
    timestamp: "2026-04-09T11:42:00-07:00",
  },
  {
    id: "interaction_004",
    case_id: "case_003",
    channel: "email",
    direction: "inbound",
    content: "Marcus sent intake information and preferred times.",
    timestamp: "2026-04-07T15:30:00-07:00",
  },
  {
    id: "interaction_005",
    case_id: "case_004",
    channel: "email",
    direction: "inbound",
    content: "Sarah confirmed Thursday, April 10 at 3:00 PM.",
    timestamp: "2026-04-04T18:30:00-07:00",
  },
];

const emailLog: MockEmailLog[] = [
  {
    id: "email_001",
    case_id: "case_001",
    to: "jane.kim@example.com",
    subject: "Tell us more",
    body: "Thanks for reaching out. A few quick questions will help me understand what you need.",
    sent_at: "2026-04-05T09:31:00-07:00",
    source_action: "send_intake_email",
  },
  {
    id: "email_002",
    case_id: "case_003",
    to: "marcus.l@example.com",
    subject: "Tell us about yourself",
    body: "Thanks for reaching out. A few quick questions will help me understand what you need.",
    sent_at: "2026-04-07T10:01:00-07:00",
    source_action: "send_intake_email",
  },
  {
    id: "email_003",
    case_id: "case_003",
    to: "marcus.l@example.com",
    subject: "Next steps for your session — Marcus",
    body: "Thanks for sharing more about what you're looking for. I think this could be a great fit and will send a few times shortly.",
    sent_at: "2026-04-08T09:00:00-07:00",
    source_action: "approve_fit",
  },
  {
    id: "email_004",
    case_id: "case_003",
    to: "marcus.l@example.com",
    subject: "Available time slots",
    body: "Here are a few times that could work for your session.",
    sent_at: "2026-04-08T09:02:00-07:00",
    source_action: "propose_time_slots",
  },
  {
    id: "email_005",
    case_id: "case_004",
    to: "sarah.m@example.com",
    subject: "Tell us about yourself",
    body: "Thanks for reaching out. A few quick questions will help me understand what you need.",
    sent_at: "2026-04-03T11:01:00-07:00",
    source_action: "send_intake_email",
  },
  {
    id: "email_006",
    case_id: "case_004",
    to: "sarah.m@example.com",
    subject: "Next steps for your session — Sarah",
    body: "Thanks for sharing more about what you're looking for. I think this could be a great fit and will send over time options next.",
    sent_at: "2026-04-04T16:00:00-07:00",
    source_action: "approve_fit",
  },
  {
    id: "email_007",
    case_id: "case_004",
    to: "sarah.m@example.com",
    subject: "Booking confirmed",
    body: "You're all set. Looking forward to your session.",
    sent_at: "2026-04-05T09:00:00-07:00",
    source_action: "confirm_booking",
  },
];

export function getSeedData(): SeedPayload {
  return {
    cases: cases.map((bookingCase) => ({ ...bookingCase })),
    drafts: drafts.map((draft) => ({ ...draft })),
    timeline: timeline.map((entry) => ({
      ...entry,
      metadata: entry.metadata ? { ...entry.metadata } : undefined,
    })),
    interactions: interactions.map((interaction) => ({ ...interaction })),
    emailLog: emailLog.map((email) => ({ ...email })),
  };
}
